name: Keep the versions up-to-date

on:
  release:
    types: [published, edited]

jobs:
  run-tag-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Actions-R-Us/actions-tagger@330ddfac760021349fef7ff62b372f2f691c20fb
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          publish_latest_tag: 'true'
